import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import CartProvider from "./context/CartProvider";
import ReviewsAndFooter from "./Footer";
import { Providers } from "./providers";


const rubik = Rubik({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});


export const metadata: Metadata = {
  title: "KICKS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubik.className} antialiased`}>
        <Providers>
          <CartProvider>
            <div className="">
              <div className="mt-8">
                <Header />
              </div>
              {children}
            </div>
          </CartProvider>
        </Providers>
        <ReviewsAndFooter />
        <div className="text-black text-center mt-[28px] mb-[18px]">© All rights reserved </div>
      </body>
    </html>
  );
}
